AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Medianet Postbacks Controller

Resources:

  MedianetReporterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt MedianetReporterFunctionRole.Arn
      Architectures:
        - arm64
      Handler: app.handler
      FunctionName: Medianet-postbacks-controller
      Description: Receives Medianet Postbacks from a Queue and forwards them to different
        destinations
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref ConversionEventsQueue
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ConversionEventsQueue
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt ConversionEventsQueue.Arn
            BatchSize: 10
      Tags:
        project: efflux
        component: medianet

  # Create a SQS queue for events to report
  ConversionEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: medianet-postbacks-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ConversionEventsQueueDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: medianet

  # Create a DLQ for the ConversionEventsQueue
  ConversionEventsQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: medianet-postbacks-queue-dlq
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: medianet

  # Log group for the lambda function
  MedianetReporterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MedianetReporterFunction}
      RetentionInDays: 7
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: medianet

  # IAM role for lambda function
  MedianetReporterFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MedianetReporterFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: '*'
              - Effect: Allow
                Action: sqs:*
                Resource: '*'
              - Effect: Allow
                Action: cloudwatch:*
                Resource: '*'
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: medianet

Outputs:
  CompilerFunctionVersion:
    Description: Lambda function version
    Value: !Ref MedianetReporterFunction.Version

  MedianetQueueUrl:
    Description: URL of the medianet Postbacks Queue
    Export:
      Name: MedianetQueueUrl
    Value: !Ref ConversionEventsQueue
