AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Crossroads Postbacks Controller

Resources:

  CrossroadsReporterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt CrossroadsReporterFunctionRole.Arn
      Architectures:
        - arm64
      Handler: app.handler
      FunctionName: Crossroads-postbacks-controller
      Description: Receives Crossroads Postbacks from a Queue and forwards them to different
        destinations
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 128
      AutoPublishAlias: live
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref ConversionEventsQueue
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref ConversionEventsQueue
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt ConversionEventsQueue.Arn
            BatchSize: 10
      Tags:
        project: efflux
        component: crossroads

  # Create a SQS queue for events to report
  ConversionEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: crossroads-postbacks-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ConversionEventsQueueDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: crossroads

  # Create a DLQ for the ConversionEventsQueue
  ConversionEventsQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: crossroads-postbacks-queue-dlq
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: crossroads

  # Log group for the lambda function
  CrossroadsReporterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CrossroadsReporterFunction}
      RetentionInDays: 7
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: crossroads

  # IAM role for lambda function
  CrossroadsReporterFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CrossroadsReporterFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: '*'
              - Effect: Allow
                Action: sqs:*
                Resource: '*'
              - Effect: Allow
                Action: cloudwatch:*
                Resource: '*'
      Tags:
        - Key: project
          Value: efflux
        - Key: operation
          Value: postbacks
        - Key: component
          Value: crossroads

Outputs:
  CompilerFunctionVersion:
    Description: Lambda function version
    Value: !Ref CrossroadsReporterFunction.Version

  CrossroadsQueueUrl:
    Description: URL of the Crossroads Postbacks Queue
    Export:
      Name: CrossroadsQueueUrl
    Value: !Ref ConversionEventsQueue
